inherit_from:
  - .rubocop.ruby.yml
  - .rubocop.rails.yml
  - .rubocop.performance.yml

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SymbolArray:
  Enabled: false

# 本に合わせるため
Rails/HelperInstanceVariable:
  Enabled: false
Metrics/AbcSize:
  Enabled: true
  Max: 25
