version: '3'

services:
  web:
    # ecs-cliでbuildはサポート対象外なため無視される
    build:
      context: ./docker/web
    image: tiwvstiw/cicdpipe_web
    ports:
      - "0:80"
    volumes:
      - public:/cicdpipe/public
      - sockets:/cicdpipe/sockets
    depends_on: 
      - app

  app:
    build:
      # buildでenvironmentを参照できないのでargsを使う
      args:
        - BUILD_CONTEXT=production
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: tiwvstiw/cicdpipe_app
    environment:
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - public:/cicdpipe/public
      - sockets:/cicdpipe/tmp/sockets
      - bundle:/bundle
    command: /bin/sh -c "./entrypoint.sh"

volumes:
  public:
  sockets:
  bundle:
