version: '3'

services:
  web:
    build:
      context: ./docker/web
    image: tiwvstiw/cicdpipe_web
    ports:
      - "80:80"
    volumes:
      - public:/cicdpipe/public
      # socketファイルの共有
      - sockets:/cicdpipe/sockets
    depends_on: 
      - app

  app:
    build:
      # buildでenvironmentを参照できないのでargsを使う
      args:
        - build_context=development
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: tiwvstiw/cicdpipe_app
    environment:
      - SPROCKETS_CACHE=/sprockets_cache
    volumes:
      - public:/cicdpipe/public
      - sockets:/cicdpipe/tmp/sockets
      - bundle:/bundle
      - sprockets_cache:/sprockets_cache
    ports:
      - "3000:3000"

  db:
    image: postgres:12.2
    environment:
      POSTGRES_USER: cicdpipe
      POSTGRES_PASSWORD: cicdpipe
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  public:
  sockets:
  bundle:
  sprockets_cache:
  db_data:
