version: '3'

services:
  web:
    build:
      context: ./docker/web
    image: tiwvstiw/cicdpipe_web
    ports:
      - "80:80"
    volumes: 
      # socketファイルの共有
      - sockets:/sockets
    depends_on: 
      - app

  app:
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - SPROCKETS_CACHE=/sprockets_cache
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    image: tiwvstiw/cicdpipe_app
    volumes:
      - sockets:/cicdpipe/tmp/sockets
      - bundle:/bundle
      - sprockets_cache:/sprockets_cache
    ports:
      - "3000:3000"

  db:
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  sockets:
  bundle:
  sprockets_cache:
  db_data:
