version: '3'

services:
  web:
    ports:
      - "80:80"

  app:
    build:
      args:
        - BUILD_CONTEXT=$BUILD_CONTEXT
    environment:
      - RAILS_LOG_TO_STDOUT=
      - SPROCKETS_CACHE=/sprockets_cache
    volumes:
      - .:/cicdpipe
      - sprockets_cache:/sprockets_cache
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres:12.2
    environment:
      POSTGRES_USER: cicdpipe
      POSTGRES_PASSWORD: cicdpipe
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  sprockets_cache:
  db_data:
